### ISSUE TITLE
Deserialization safety

### ISSUE THREAD

**Issue by daxpedda** [novifinancial/voprf#25]
Currently some data-structures contain fields like `data: Vec<u8>`, during de-serialization the user obviously can check for potential attackers by limiting the size of data to not be GBs and such.

But we know that `NonVerifiableClient`s data can't be bigger then 64 bytes for example (I think), therefore I see the potential to help out here a little bit.

We could definitely start by returning an error if `data` exceeds a certain size. Additionally we could just use [`ArrayVec`](https://docs.rs/arrayvec/0.7.1/arrayvec/struct.ArrayVec.html) (or implement our own type if we don't want to pull an additional dependency) to do the check for us and additionally remove unnecessary allocations.

I am prepared to do the PR of course.

**Comment by kevinlewi** [comment]
According to the current state of the draft, I believe data cannot exceed 2^16 bytes (based on the fact that it is passed to i2osp(data, 2) during serialization, which would throw a serialization error if this was exceeded). So would the idea here be to frontload the error so that it fires upon initialization of the client structs that set data field, or is the intention to enforce a more stringent limit (such as 64 bytes) on the input?

Personally I feel that enforcing a more stringent limit might not be necessary, since perhaps some applications would want to take advantage of a larger input.

**Comment by daxpedda** [comment]
I made two mistakes here:
1. I was looking at inputs we used in tests for `blind`, which I didn't realize is the public API at the time, this is non-sense ofc, that's the whole point here
2. Clearly I didn't think this through, because `NonVerifiableClients` doesn't get sent anywhere, no de-serialization safety necessary, the point is to blind the data anyway, not send it anywhere

Let's pretend this never happened :flushed:.
